{
 "title": "Homework",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{}[$__rate_interval]))\r",
     "legendFormat": "Load Average 1m"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{}[$__rate_interval]))",
     "legendFormat": "Load Average 5m"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{}[$__rate_interval]))",
     "legendFormat": "Load Average 15m"
    }
   ]
  },
  {
   "title": "RAM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\"} - node_memory_MemFree_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU idle %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by(instance)(rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[$__rate_interval])) * 100",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=\"ext4\",instance=\"nodeexporter:9100\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_free_bytes{fstype=\"ext4\",instance=\"nodeexporter:9100\"}",
     "legendFormat": "free"
    }
   ]
  }
 ]
}